runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /.*
  script: abhisheksatpathy.app

- url: /(.*\.(gif|png|jpg|svg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|svg)$